services:

  library-proxy:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: library-proxy

    ports:
      - "8081:8081"

    networks:
      - library-network

networks:
  library-network:
    external: true